# fly.toml file generated for localizacion on 2023-03-24T18:31:32-06:00

app = "localizacion"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gdl"
processes = []

[build]
  image = "rickytm/localizacion:latest"

[env]
  ASPNETCORE_URLS = "http://+:5000"

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
